version: '3.8'

services:
  node-service:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      DB_HOST: db
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    deploy:
      replicas: 3  # This tells Docker Compose to start 3 instances of node-service

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DB_HOST: db
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - node-service

volumes:
  db_data:
